import type { Song } from '../types/song';
import { SONG_ID_PATTERN, MAX_SONG_ID_LENGTH } from './songId';
import { songToRow, type SongRow } from './supabaseSongRepository';

/**
 * The one-time import of the songs bundled with the app into `songs`, with
 * their ids exactly as they are (favourites, recents, setlists, arrangements,
 * key preferences and history point at them), and version 1 of each.
 *
 * The SQL is generated from the bundled data (scripts/generate-catalog-import.ts)
 * and runs all or nothing: an id already taken, a failed constraint, a row
 * that doesn't read back identical, or a count other than expected aborts it.
 */

/** The table's CHECK constraints (migration 20260918120000), mirrored to audit the rows before any import. */
export function rowProblems(row: SongRow): string[] {
  const problems: string[] = [];
  const length = (value: string | null) => (value === null ? 0 : [...value].length);
  if (!SONG_ID_PATTERN.test(row.id) || row.id.length > MAX_SONG_ID_LENGTH) problems.push('id');
  if (length(row.title.trim()) < 1 || length(row.title.trim()) > 120) problems.push('title');
  if (length(row.artist) > 120) problems.push('artist');
  if (row.original_key !== null && (length(row.original_key) < 1 || length(row.original_key) > 8)) problems.push('original_key');
  if (row.recommended_capo !== null && (row.recommended_capo < 0 || row.recommended_capo > 11)) problems.push('recommended_capo');
  if (row.time_signature !== null && !/^[0-9]{1,2}\/(2|4|8|16)$/.test(row.time_signature)) problems.push('time_signature');
  if (row.tempo !== null && (!Number.isInteger(row.tempo) || row.tempo < 30 || row.tempo > 300)) problems.push('tempo');
  if (length(row.rhythm_pattern) > 120) problems.push('rhythm_pattern');
  if (length(row.content) < 1 || length(row.content) > 20000) problems.push('content');
  if (row.difficulty !== null && !['Fácil', 'Intermedio', 'Avanzado'].includes(row.difficulty)) problems.push('difficulty');
  if (row.year !== null && !/^[0-9]{4}$/.test(row.year)) problems.push('year');
  if (row.youtube_id !== null && !/^[A-Za-z0-9_-]{11}$/.test(row.youtube_id)) problems.push('youtube_id');
  return problems;
}

export interface CatalogAudit {
  total: number;
  duplicateIds: string[];
  invalidRows: Array<{ id: string; problems: string[] }>;
}

export function auditCatalogRows(songs: readonly Song[]): CatalogAudit {
  const seen = new Set<string>();
  const duplicateIds: string[] = [];
  for (const song of songs) {
    if (seen.has(song.id)) duplicateIds.push(song.id);
    seen.add(song.id);
  }
  const invalidRows = songs
    .map((song) => ({ id: song.id, problems: rowProblems(songToRow(song)) }))
    .filter((entry) => entry.problems.length > 0);
  return { total: songs.length, duplicateIds, invalidRows };
}

const COLUMNS = `id text, title text, artist text, original_key text, recommended_capo smallint, time_signature text,
    tempo smallint, rhythm_pattern text, categories text[], liturgical_seasons text[], tags text[], content text,
    chords_used text[], difficulty text, year text, youtube_id text`;

const COLUMN_NAMES = [
  'id',
  'title',
  'artist',
  'original_key',
  'recommended_capo',
  'time_signature',
  'tempo',
  'rhythm_pattern',
  'categories',
  'liturgical_seasons',
  'tags',
  'content',
  'chords_used',
  'difficulty',
  'year',
  'youtube_id',
] as const;

/**
 * The import as one PL/pgSQL block. With `dryRun`, it does everything and then
 * raises its report, so the transaction is rolled back and nothing stays.
 */
export function buildCatalogImportSql(songs: readonly Song[], { dryRun, source }: { dryRun: boolean; source: string }): string {
  const audit = auditCatalogRows(songs);
  if (audit.duplicateIds.length || audit.invalidRows.length) throw new Error('El catálogo no pasa la auditoría: no se genera la importación.');
  const json = JSON.stringify(songs.map(songToRow));
  if (json.includes('$rows$')) throw new Error('El contenido contiene el delimitador $rows$.');
  const same = COLUMN_NAMES.filter((name) => name !== 'id').map((name) => `s.${name} is not distinct from x.${name}`).join('\n        and ');

  return `-- GENERATED by scripts/generate-catalog-import.ts from ${source}. Do not edit by hand.
-- ${dryRun ? 'DRY RUN: does the whole import, checks it, and rolls everything back.' : 'Imports the bundled songs into public.songs (ids unchanged) and writes version 1 of each.'}
-- All or nothing: an id already taken, a failed constraint or any difference aborts it.
do $import$
declare
  v_expected constant integer := ${songs.length};
  v_rows constant jsonb := $rows$${json}$rows$::jsonb;
  v_taken integer;
  v_songs integer;
  v_versions integer;
  v_identical integer;
begin
  if jsonb_array_length(v_rows) <> v_expected then
    raise exception 'GENESARET:import:count';
  end if;

  select count(*) into v_taken
  from public.songs s join jsonb_to_recordset(v_rows) as x(id text) on x.id = s.id;
  if v_taken > 0 then
    raise exception 'GENESARET:import:ids_taken (%)', v_taken;
  end if;

  insert into public.songs (${COLUMN_NAMES.join(', ')}, status, current_version)
  select ${COLUMN_NAMES.map((name) => `x.${name}`).join(', ')}, 'published', 1
  from jsonb_to_recordset(v_rows) as x(${COLUMNS});
  get diagnostics v_songs = row_count;

  -- Version 1: the published row as it now is, like approve_submission writes it.
  -- No submission and no reviewer: these songs predate the editorial workflow.
  insert into public.song_versions (song_id, version, snapshot, submission_id, published_by)
  select s.id, 1, to_jsonb(s), null, null
  from public.songs s join jsonb_to_recordset(v_rows) as x(id text) on x.id = s.id;
  get diagnostics v_versions = row_count;

  -- Lossless: every column reads back exactly as sent.
  select count(*) into v_identical
  from public.songs s join jsonb_to_recordset(v_rows) as x(${COLUMNS}) on x.id = s.id
  where ${same};

  if v_songs <> v_expected or v_versions <> v_expected or v_identical <> v_expected then
    raise exception 'GENESARET:import:mismatch songs=% versions=% identical=%', v_songs, v_versions, v_identical;
  end if;
${
  dryRun
    ? `
  raise exception 'DRY-RUN OK: songs=% versions=% identical=% (todo revertido)', v_songs, v_versions, v_identical;`
    : `
  raise notice 'Importadas % canciones con su versión 1.', v_songs;`
}
end;
$import$;
`;
}
