import { parseSongDraft, type SongDraft } from './songDraft';
import { validateSongDraft, type SongValidationIssue, type SongValidationOptions } from './validateSongDraft';

/**
 * A submission is a proposal: a new song, or a correction of a published one.
 * It never changes the catalog by itself. Only an approval, done by the
 * backend for an authorized reviewer, publishes it (see the migration's
 * approve_submission function).
 */

export type SongSubmissionType = 'create' | 'update';
export type SongSubmissionStatus = 'pending' | 'changes_requested' | 'rejected' | 'approved';

export const SUBMISSION_STATUS_LABELS: Record<SongSubmissionStatus, string> = {
  pending: 'En revisión',
  changes_requested: 'Cambios solicitados',
  rejected: 'No aprobada',
  approved: 'Aprobada',
};

export const SUBMISSION_PAYLOAD_SCHEMA_VERSION = 1;
export const MAX_CONTRIBUTOR_NAME_LENGTH = 80;
export const MAX_CONTRIBUTOR_EMAIL_LENGTH = 254;
/** A whole proposal, as JSON; the database enforces the same limit */
export const MAX_SUBMISSION_BYTES = 65_536;

/**
 * Who sent it: both optional, and nothing else is ever asked. The email is
 * only for the review team to reply; it is never published, never returned by
 * the public status check, and never part of the song.
 */
export interface SongSubmissionContributor {
  name: string | null;
  email: string | null;
}

/** What a visitor sends. The song travels whole, exactly as written. */
export interface SongSubmissionPayload {
  schemaVersion: typeof SUBMISSION_PAYLOAD_SCHEMA_VERSION;
  type: SongSubmissionType;
  /** The published song a correction is for; null for a new song */
  targetSongId: string | null;
  /**
   * A correction only: the published version it was made on. The database
   * stores it only while it is still the current version ("stale" otherwise),
   * and publishes the correction only if it still is when approved.
   */
  baseVersion?: number;
  song: SongDraft;
  contributor: SongSubmissionContributor;
  /**
   * Makes sending safe to retry. Generated once by the browser before the
   * first attempt and reused on every retry of the same proposal: if the
   * first attempt reached the database but its answer was lost, the retry
   * gets the same tracking code back instead of creating a second proposal.
   */
  requestId?: string;
  /**
   * The secret for editing this proposal later, generated by the browser
   * (64 hex characters). The database stores only its SHA-256, and a retry is
   * recognised only when it carries the same token.
   */
  editToken?: string;
}

/**
 * A stored submission, as the review side sees it. Only reviewers read this
 * (through the database's policies); the public never receives it.
 */
export interface SongSubmission {
  id: string;
  type: SongSubmissionType;
  targetSongId: string | null;
  proposedSong: SongDraft;
  status: SongSubmissionStatus;
  contributorName: string | null;
  contributorEmail: string | null;
  trackingCode: string;
  /** Written by the reviewer for the contributor; public once the review is done */
  reviewNote: string | null;
  submittedAt: string;
  reviewedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

/**
 * What the sender gets back, once. The tracking code checks the status; the
 * edit token is a separate secret kept for a later "edit my submission"
 * without an account. The database only stores a hash of the token.
 */
export interface SubmissionReceipt {
  trackingCode: string;
  editToken: string;
}

/** The only view of a submission anyone can get with a tracking code. */
export interface PublicSubmissionStatus {
  trackingCode: string;
  type: SongSubmissionType;
  title: string;
  status: SongSubmissionStatus;
  /** Only once reviewed; never while pending */
  reviewNote: string | null;
  submittedAt: string;
  reviewedAt: string | null;
}

/** The safe projection, field by field: nothing is copied that isn't listed here. */
export function toPublicStatus(submission: SongSubmission): PublicSubmissionStatus {
  return {
    trackingCode: submission.trackingCode,
    type: submission.type,
    title: submission.proposedSong.title,
    status: submission.status,
    reviewNote: submission.status === 'pending' ? null : submission.reviewNote,
    submittedAt: submission.submittedAt,
    reviewedAt: submission.reviewedAt,
  };
}

export function buildSubmissionPayload(
  song: SongDraft,
  {
    type,
    targetSongId = null,
    contributor = { name: null, email: null },
    attempt,
    baseVersion,
  }: {
    type: SongSubmissionType;
    targetSongId?: string | null;
    /** Required for a correction: the version of the song it was made on */
    baseVersion?: number;
    contributor?: Partial<SongSubmissionContributor>;
    /** The retry identity of this proposal (see SubmissionAttempt) */
    attempt?: SubmissionAttempt;
  }
): SongSubmissionPayload {
  const clean = (value: string | null | undefined) => (value && value.trim() ? value.trim() : null);
  return {
    schemaVersion: SUBMISSION_PAYLOAD_SCHEMA_VERSION,
    type,
    targetSongId: type === 'update' ? targetSongId : null,
    ...(type === 'update' && baseVersion !== undefined ? { baseVersion } : {}),
    song,
    contributor: { name: clean(contributor.name), email: clean(contributor.email)?.toLowerCase() ?? null },
    ...(attempt ? { requestId: attempt.requestId, editToken: attempt.editToken } : {}),
  };
}

/** One proposal's identity across retries: created before the first attempt, kept until it succeeds. */
export interface SubmissionAttempt {
  requestId: string;
  editToken: string;
}

/** Same bounds as the database: a positive integer of at most nine digits. */
export function isBaseVersion(value: unknown): value is number {
  return Number.isInteger(value) && (value as number) >= 1 && (value as number) <= 999_999_999;
}

/**
 * Whether a proposed song changes anything of the published one: the fields
 * the database compares before storing a correction (it refuses one that
 * changes nothing). The chord list is left out, it follows the content.
 */
export function songDraftChanges(published: SongDraft, proposed: SongDraft): boolean {
  const text = (value: string | null) => (value === null || value.trim() === '' ? null : value.trim());
  const blank = (value: string | null) => (value === '' ? null : value);
  const same = (a: unknown, b: unknown) => JSON.stringify(a) === JSON.stringify(b);
  return !(
    proposed.title.trim() === published.title &&
    text(proposed.artist) === published.artist &&
    blank(proposed.originalKey) === published.originalKey &&
    proposed.recommendedCapo === published.recommendedCapo &&
    blank(proposed.timeSignature) === published.timeSignature &&
    proposed.tempo === published.tempo &&
    blank(proposed.rhythmPattern) === published.rhythmPattern &&
    same(proposed.categories, published.categories) &&
    same(proposed.liturgicalSeasons, published.liturgicalSeasons) &&
    same(proposed.tags, published.tags) &&
    proposed.content === published.content &&
    proposed.difficulty === published.difficulty &&
    blank(proposed.year) === published.year &&
    blank(proposed.youtubeId) === published.youtubeId
  );
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const TOKEN = /^[0-9a-f]{64}$/;

export function createSubmissionAttempt(random: (length: number) => Uint8Array = (length) => crypto.getRandomValues(new Uint8Array(length))): SubmissionAttempt {
  const hex = (bytes: Uint8Array) => [...bytes].map((byte) => byte.toString(16).padStart(2, '0')).join('');
  const id = random(16);
  // RFC 4122 version 4 layout.
  id[6] = (id[6] & 0x0f) | 0x40;
  id[8] = (id[8] & 0x3f) | 0x80;
  const h = hex(id);
  return {
    requestId: `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`,
    editToken: hex(random(32)),
  };
}

export function isSubmissionAttempt(value: unknown): value is SubmissionAttempt {
  if (typeof value !== 'object' || value === null) return false;
  const entry = value as Record<string, unknown>;
  return typeof entry.requestId === 'string' && UUID.test(entry.requestId) && typeof entry.editToken === 'string' && TOKEN.test(entry.editToken);
}

export type SubmissionIssueCode =
  | 'type-invalid'
  | 'target-required'
  | 'target-unknown'
  | 'base-version-invalid'
  | 'no-changes'
  | 'contributor-name-too-long'
  | 'contributor-email-invalid'
  | 'too-large'
  | 'song-invalid';

export interface SubmissionValidationResult {
  ok: boolean;
  errors: Array<{ code: SubmissionIssueCode; message: string }>;
  /** The song's own check, errors and warnings, for the editor to show in place */
  song: { errors: SongValidationIssue[]; warnings: SongValidationIssue[] };
}

// Deliberately simple: something@something.tld. The real check is the reply.
const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;

/**
 * Everything checked before sending. The database checks the same limits
 * again: this is for the person writing, not the security boundary.
 */
export function validateSubmissionPayload(
  payload: SongSubmissionPayload,
  options: SongValidationOptions & {
    publishedSongIds?: ReadonlySet<string>;
    /** A correction: the song as published, so a proposal that changes nothing is caught before sending */
    publishedSong?: SongDraft;
  } = {}
): SubmissionValidationResult {
  const errors: SubmissionValidationResult['errors'] = [];
  if (payload.type !== 'create' && payload.type !== 'update') errors.push({ code: 'type-invalid', message: 'Tipo de propuesta desconocido.' });
  if (payload.type === 'update') {
    if (!payload.targetSongId) errors.push({ code: 'target-required', message: 'Falta la canción que se corrige.' });
    else if (options.publishedSongIds && !options.publishedSongIds.has(payload.targetSongId)) {
      errors.push({ code: 'target-unknown', message: 'La canción que se corrige no está en el catálogo.' });
    }
    if (!isBaseVersion(payload.baseVersion)) {
      errors.push({ code: 'base-version-invalid', message: 'Falta la versión de la canción sobre la que se hizo la corrección.' });
    }
    if (options.publishedSong && !songDraftChanges(options.publishedSong, payload.song)) {
      errors.push({ code: 'no-changes', message: 'La propuesta no cambia nada de la canción publicada.' });
    }
  } else if (payload.baseVersion !== undefined) {
    errors.push({ code: 'base-version-invalid', message: 'Una canción nueva no tiene versión base.' });
  }
  const { name, email } = payload.contributor;
  if (name && name.length > MAX_CONTRIBUTOR_NAME_LENGTH) {
    errors.push({ code: 'contributor-name-too-long', message: `El nombre no puede pasar de ${MAX_CONTRIBUTOR_NAME_LENGTH} caracteres.` });
  }
  if (email && (email.length > MAX_CONTRIBUTOR_EMAIL_LENGTH || !EMAIL.test(email))) {
    errors.push({ code: 'contributor-email-invalid', message: 'El correo no parece válido.' });
  }
  if (new TextEncoder().encode(JSON.stringify(payload)).length > MAX_SUBMISSION_BYTES) {
    errors.push({ code: 'too-large', message: 'La propuesta es demasiado grande.' });
  }
  const song = validateSongDraft(payload.song, options);
  if (!song.ok) errors.push({ code: 'song-invalid', message: 'La canción tiene errores que corregir.' });
  return { ok: errors.length === 0, errors, song: { errors: song.errors, warnings: song.warnings } };
}

/** A payload from untrusted JSON, or null. */
export function parseSubmissionPayload(value: unknown): SongSubmissionPayload | null {
  if (typeof value !== 'object' || value === null) return null;
  const entry = value as Record<string, unknown>;
  if (entry.schemaVersion !== SUBMISSION_PAYLOAD_SCHEMA_VERSION) return null;
  if (entry.type !== 'create' && entry.type !== 'update') return null;
  const song = parseSongDraft(entry.song);
  if (!song) return null;
  const contributor = (typeof entry.contributor === 'object' && entry.contributor !== null ? entry.contributor : {}) as Record<string, unknown>;
  return {
    schemaVersion: SUBMISSION_PAYLOAD_SCHEMA_VERSION,
    type: entry.type,
    targetSongId: typeof entry.targetSongId === 'string' ? entry.targetSongId : null,
    ...(entry.type === 'update' && isBaseVersion(entry.baseVersion) ? { baseVersion: entry.baseVersion } : {}),
    song,
    contributor: {
      name: typeof contributor.name === 'string' ? contributor.name : null,
      email: typeof contributor.email === 'string' ? contributor.email : null,
    },
  };
}

/**
 * A proposal read back by its author to correct it (tracking code + edit
 * token). Only the author's own content and the reviewer's note: never the
 * contact data.
 */
export interface SubmissionForEdit {
  trackingCode: string;
  type: SongSubmissionType;
  status: SongSubmissionStatus;
  reviewNote: string | null;
  /** Null when what is stored can't be read as a song */
  song: SongDraft | null;
  /** A correction: the published song it is for */
  targetSongId: string | null;
  /** A correction: the version it was made on (null for older corrections, which predate versions) */
  baseVersion: number | null;
  /** That version as it was published, to show the author their own changes; null when unknown */
  baseSong: SongDraft | null;
}

export interface ResubmitInput {
  trackingCode: string;
  editToken: string;
  song: SongDraft;
  /** A correction: the published version the corrected proposal is made on now */
  baseVersion?: number;
}

export interface ResubmitReceipt {
  trackingCode: string;
  status: SongSubmissionStatus;
}
