/**
 * Tracking codes: "GS-4K8P-2QMX". They let someone who sent a song check how
 * its review is going, and nothing else: a code is not a password, it opens
 * no editing, approving or personal data.
 *
 * They are random, never a counter (a counter would let anyone walk through
 * everyone's submissions). 8 characters from a 29-character alphabet give
 * about 5 × 10^11 codes (≈39 bits); the database also keeps them unique. The
 * alphabet leaves out 0/O, 1/I/L and U/V, which are easy to confuse, so a code
 * can be read aloud or copied by hand.
 *
 * The real codes are generated by the database when a submission is stored
 * (see the migration); this module generates them the same way for local and
 * test adapters, and reads what people type.
 */

export const TRACKING_ALPHABET = '23456789ABCDEFGHJKMNPQRSTWXYZ';
export const TRACKING_PREFIX = 'GS';
export const TRACKING_LENGTH = 8;

const PATTERN = new RegExp(`^${TRACKING_PREFIX}-[${TRACKING_ALPHABET}]{4}-[${TRACKING_ALPHABET}]{4}$`);

/** Random bytes from the platform's cryptographic generator (browser or Node). */
export type RandomBytes = (length: number) => Uint8Array;

const cryptoRandom: RandomBytes = (length) => crypto.getRandomValues(new Uint8Array(length));

/** A new code. Bytes that would bias the alphabet are thrown away and drawn again. */
export function generateTrackingCode(random: RandomBytes = cryptoRandom): string {
  const size = TRACKING_ALPHABET.length;
  const limit = 256 - (256 % size);
  let chars = '';
  while (chars.length < TRACKING_LENGTH) {
    for (const byte of random(TRACKING_LENGTH)) {
      if (byte < limit && chars.length < TRACKING_LENGTH) chars += TRACKING_ALPHABET[byte % size];
    }
  }
  return `${TRACKING_PREFIX}-${chars.slice(0, 4)}-${chars.slice(4)}`;
}

export function isTrackingCode(value: string): boolean {
  return PATTERN.test(value);
}

/**
 * What someone typed, as a code: case, spaces and dashes don't matter, and the
 * prefix may be left out. A character outside the alphabet makes it invalid
 * rather than guessed. Null when it can't be a code.
 */
export function normalizeTrackingCode(input: string): string | null {
  const compact = input.toUpperCase().replace(/[\s-]/g, '');
  // By length, not by prefix: a code body may itself start with "GS".
  const body = compact.length === TRACKING_PREFIX.length + TRACKING_LENGTH && compact.startsWith(TRACKING_PREFIX)
    ? compact.slice(TRACKING_PREFIX.length)
    : compact;
  if (body.length !== TRACKING_LENGTH) return null;
  const code = `${TRACKING_PREFIX}-${body.slice(0, 4)}-${body.slice(4)}`;
  return isTrackingCode(code) ? code : null;
}
