-- =============================================================================
-- GENESARET · Phase 6C
-- The contributor corrects their own proposal when the team asks for changes.
--
--   changes_requested -> (same browser, edit token) -> corrected -> Turnstile -> pending
--
-- The edit token (64 hex, generated by the sender's browser, only its SHA-256
-- stored) is the proof of authorship: no account, no email link. Earlier
-- migrations are applied and never edited; this one only adds.
-- =============================================================================

-- How many times a proposal came back corrected, and when it last did.
alter table public.song_submissions
  add column resubmission_count integer not null default 0 check (resubmission_count between 0 and 20),
  add column resubmitted_at timestamptz;

-- -----------------------------------------------------------------------------
-- get_submission_for_edit: the author reads their own proposal back
-- -----------------------------------------------------------------------------
-- Needs the tracking code AND the edit token; returns the proposed song (the
-- author's own content) and the reviewer's note. Never the contact data. Uses
-- the same rate limit as the status check. A wrong token and a missing code
-- look the same: nothing.

create or replace function public.get_submission_for_edit(p_tracking_code text, p_edit_token text)
returns table (tracking_code text, type text, status text, review_note text, proposed_song jsonb)
language plpgsql
volatile
security definer
set search_path = ''
as $$
#variable_conflict use_column
declare
  v_code text := upper(btrim(coalesce(p_tracking_code, '')));
  v_token text := coalesce(p_edit_token, '');
  v_source_hash text := public.request_source_hash();
begin
  if v_code !~ '^GS-[23456789ABCDEFGHJKMNPQRSTWXYZ]{4}-[23456789ABCDEFGHJKMNPQRSTWXYZ]{4}$' or v_token !~ '^[0-9a-f]{64}$' then
    return;
  end if;

  delete from public.submission_rate_events e where e.created_at < now() - interval '1 day';
  if (select count(*) from public.submission_rate_events e
      where e.kind = 'status' and e.source_hash = v_source_hash and e.created_at > now() - interval '10 minutes') >= 30
     or (select count(*) from public.submission_rate_events e
         where e.kind = 'status' and e.created_at > now() - interval '1 hour') >= 3000 then
    raise exception 'GENESARET:rate_limited';
  end if;
  insert into public.submission_rate_events (source_hash, kind) values (v_source_hash, 'status');

  return query
  select s.tracking_code, s.type, s.status,
         case when s.status = 'pending' then null else s.review_note end,
         s.proposed_song
  from public.song_submissions s
  where s.tracking_code = v_code
    and s.edit_token_hash = encode(extensions.digest(v_token, 'sha256'), 'hex')
  limit 1;
end;
$$;

revoke execute on function public.get_submission_for_edit(text, text) from public;
grant execute on function public.get_submission_for_edit(text, text) to anon, authenticated;

-- -----------------------------------------------------------------------------
-- resubmit_song_submission_verified: the corrected proposal goes back to review
-- -----------------------------------------------------------------------------
-- Only the Edge Function submit-song calls it (service_role), after Turnstile
-- passed, with the visitor's IP for the same send rate limit as a new
-- proposal. Only a proposal in 'changes_requested', only with its edit token,
-- and only the song changes: type, target, contact data and dates stay.

create or replace function public.resubmit_song_submission_verified(
  p_tracking_code text,
  p_edit_token text,
  p_song jsonb,
  p_client_ip text
)
returns table (tracking_code text, status text)
language plpgsql
volatile
security definer
set search_path = ''
as $$
#variable_conflict use_column
declare
  v_code text := upper(btrim(coalesce(p_tracking_code, '')));
  v_token text := coalesce(p_edit_token, '');
  v_submission public.song_submissions%rowtype;
  v_title text;
  v_content text;
  v_source_hash text;
begin
  if v_code !~ '^GS-[23456789ABCDEFGHJKMNPQRSTWXYZ]{4}-[23456789ABCDEFGHJKMNPQRSTWXYZ]{4}$' or v_token !~ '^[0-9a-f]{64}$' then
    raise exception 'GENESARET:invalid:token';
  end if;

  -- The same checks on the song as a new proposal.
  if p_song is null or jsonb_typeof(p_song) <> 'object' or octet_length(p_song::text) > 65536
     or p_song -> 'schemaVersion' is distinct from '1'::jsonb then
    raise exception 'GENESARET:invalid:song';
  end if;
  v_title := btrim(coalesce(p_song ->> 'title', ''));
  v_content := coalesce(p_song ->> 'content', '');
  if char_length(v_title) not between 1 and 120 or char_length(btrim(v_content)) = 0 or char_length(v_content) > 20000 then
    raise exception 'GENESARET:invalid:song';
  end if;

  -- The same send limit as a new proposal: 5 per source in 10 minutes, 200 in total per hour.
  v_source_hash := encode(extensions.digest(coalesce(nullif(btrim(p_client_ip), ''), 'unknown'), 'sha256'), 'hex');
  delete from public.submission_rate_events e where e.created_at < now() - interval '1 day';
  if (select count(*) from public.submission_rate_events e
      where e.kind = 'submit' and e.source_hash = v_source_hash and e.created_at > now() - interval '10 minutes') >= 5
     or (select count(*) from public.submission_rate_events e
         where e.kind = 'submit' and e.created_at > now() - interval '1 hour') >= 200 then
    raise exception 'GENESARET:rate_limited';
  end if;
  insert into public.submission_rate_events (source_hash, kind) values (v_source_hash, 'submit');

  -- Locked: a reviewer deciding at the same moment waits, and then sees the new state.
  select * into v_submission from public.song_submissions s where s.tracking_code = v_code for update;
  -- A wrong token and a missing code answer the same.
  if not found or v_submission.edit_token_hash <> encode(extensions.digest(v_token, 'sha256'), 'hex') then
    raise exception 'GENESARET:invalid:token';
  end if;
  if v_submission.status <> 'changes_requested' then
    raise exception 'GENESARET:not_editable';
  end if;
  if v_submission.resubmission_count >= 20 then
    raise exception 'GENESARET:invalid:too_many_resubmissions';
  end if;
  if v_submission.type = 'update' and not exists (
    select 1 from public.songs s where s.id = v_submission.target_song_id and s.status = 'published'
  ) then
    raise exception 'GENESARET:invalid:target';
  end if;

  update public.song_submissions s set
    proposed_song = p_song,
    status = 'pending',
    resubmission_count = s.resubmission_count + 1,
    resubmitted_at = now()
  where s.id = v_submission.id;

  return query select v_submission.tracking_code, 'pending'::text;
end;
$$;

-- Supabase grants new functions to anon and authenticated by default: taken away.
revoke execute on function public.resubmit_song_submission_verified(text, text, jsonb, text) from public, anon, authenticated;
grant execute on function public.resubmit_song_submission_verified(text, text, jsonb, text) to service_role;
